#!/bin/bash
#SBATCH --mem=250g
#SBATCH --time=24:00:00
#SBATCH --output=log-%j.out
#SBATCH --error=log-%j.err

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.3_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.4_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.4_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.4_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.4_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.4_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.5_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.5_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.5_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.5_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.5_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.6_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.6_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.6_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.6_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.6_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.7_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.7_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.7_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.7_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.7_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.8_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.8_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.8_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.8_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.8_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_0.9_de_rq_103122/ref_labels_filtered.csv

Rscript tools/r_tools.R /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_1_de_rq_103122/query_counts.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_1_de_rq_103122/ sctype,scsorter,scina,singler,scpred /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_1_de_rq_103122/markers.txt /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_1_de_rq_103122/ref_counts_filtered.csv /home/groups/ConradLab/daniel/sharp_data/sharp_sims_de_testing/splat_1_de_rq_103122/ref_labels_filtered.csv
